baseURL = 'https://benjamin-hornigold.github.io/death_of_meaning/'
languageCode = 'en-us'
title = 'Death of meaning'
theme = 'PaperMod'

[params]
  comments = true
  defaultTheme = "dark"

[params.author]
  name = "Hornigold"
